// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/loginServer.game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LoginServer.Game {

  /// <summary>Holder for reflection information generated from Protos/loginServer.game.proto</summary>
  public static partial class LoginServerGameReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/loginServer.game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginServerGameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1Qcm90b3MvbG9naW5TZXJ2ZXIuZ2FtZS5wcm90bxIQbG9naW5TZXJ2ZXIu",
            "Z2FtZSLOAwoIQ2FyZFR5cGUSEAoIY2FyZE5hbWUYASABKAkSNQoIdHJhbnNt",
            "aXQYAiABKA4yIy5sb2dpblNlcnZlci5nYW1lLkNhcmRfVHJhbnNtaXRUeXBl",
            "EjcKCWRpcmVjdGlvbhgDIAEoDjIkLmxvZ2luU2VydmVyLmdhbWUuQ2FyZF9E",
            "aXJlY3Rpb25UeXBlEi8KBWNvbG9yGAQgASgOMiAubG9naW5TZXJ2ZXIuZ2Ft",
            "ZS5DYXJkX0NvbG9yVHlwZRItCgRsb2NrGAUgASgOMh8ubG9naW5TZXJ2ZXIu",
            "Z2FtZS5DYXJkX0xvY2tUeXBlEjMKB3hpYW9ndW8YBiABKA4yIi5sb2dpblNl",
            "cnZlci5nYW1lLkNhcmRfWGlhb0d1b1R5cGUSPwoNZ29uZ2thaXdlbmJlbhgH",
            "IAEoDjIoLmxvZ2luU2VydmVyLmdhbWUuQ2FyZF9Hb25nS2FpV2VuQmVuVHlw",
            "ZRI3CgltaW1peGlhZGEYCCABKA4yJC5sb2dpblNlcnZlci5nYW1lLkNhcmRf",
            "TWlNaVhpYURhVHlwZRIxCgZzaGl0YW4YCSABKA4yIS5sb2dpblNlcnZlci5n",
            "YW1lLkNhcmRfU2hpVGFuVHlwZSIgCg1HYW1lU3RhcnRfQzJTEg8KB3Jvb21O",
            "dWIYASABKAUieQoNR2FtZVN0YXJ0X1MyQxI2CgRjb2RlGAEgASgOMigubG9n",
            "aW5TZXJ2ZXIuZ2FtZS5HYW1lU3RhcnRfUzJDLlJldF9Db2RlEgsKA21zZxgC",
            "IAEoCSIjCghSZXRfQ29kZRILCgdTdWNjZXNzEAASCgoGRmFpbGVkEAEiQAoM",
            "SWRlbnRpdHlfUzJDEjAKCGlkZW50aXR5GAEgASgOMh4ubG9naW5TZXJ2ZXIu",
            "Z2FtZS5JZGVudGl0eVR5cGUiWwoTQ2hhcmFjdGVyQ2hvb3NlX0MyUxIQCgh1",
            "c2VyTmFtZRgBIAEoCRIyCgljaGFyYWN0ZXIYAiABKA4yHy5sb2dpblNlcnZl",
            "ci5nYW1lLkNoYXJhY3RlclR5cGUiTgoXQ2hhcmFjdGVyQ2hvb3NlTGlzdF9T",
            "MkMSMwoKY2hhcmFjdGVycxgBIAMoDjIfLmxvZ2luU2VydmVyLmdhbWUuQ2hh",
            "cmFjdGVyVHlwZSISChBHYW1lQ29tcGxldGVfUzJDIg8KDURlYWxDYXJkc19T",
            "MkMqcQoMSWRlbnRpdHlUeXBlEhUKEUlkZW50aXR5VHlwZV9Ob25lEAASFwoT",
            "SWRlbnRpdHlUeXBlX1RlR29uZxABEhgKFElkZW50aXR5VHlwZV9KdW5RaW5n",
            "EAISFwoTSWRlbnRpdHlUeXBlX1FpYW5GdRADKvIFCg1DaGFyYWN0ZXJUeXBl",
            "EhYKEkNoYXJhY3RlclR5cGVfTm9uZRAAEhgKFENoYXJhY3RlclR5cGVfTGFv",
            "SmluEAESGQoVQ2hhcmFjdGVyVHlwZV9EYU1laU52EAISGgoWQ2hhcmFjdGVy",
            "VHlwZV9FTWVpRmVuZxADEhsKF0NoYXJhY3RlclR5cGVfQmVpTGVpTWFvEAQS",
            "GQoVQ2hhcmFjdGVyVHlwZV9EYW9GZW5nEAUSFwoTQ2hhcmFjdGVyVHlwZV9E",
            "YWlMaRAGEhoKFkNoYXJhY3RlclR5cGVfSHVhbmdRdWUQBxIZChVDaGFyYWN0",
            "ZXJUeXBlX1NoYW5MaW4QCBIXChNDaGFyYWN0ZXJUeXBlX0Z1U2hlEAkSHAoY",
            "Q2hhcmFjdGVyVHlwZV9ZaURpYW5ZdWFuEAoSGAoUQ2hhcmFjdGVyVHlwZV9M",
            "aXVKaWUQCxIYChRDaGFyYWN0ZXJUeXBlX0Z1UGluZxAMEiEKHUNoYXJhY3Rl",
            "clR5cGVfUWluZ0Jhb0NodVpoYW5nEA0SIQodQ2hhcmFjdGVyVHlwZV9aaGlN",
            "aW5YaWFuZ1NodWkQDhIfChtDaGFyYWN0ZXJUeXBlX0d1YWlEYW9KaXVKaXUQ",
            "DxIfChtDaGFyYWN0ZXJUeXBlX0dhbmdUaWVUZUdvbmcQEBIeChpDaGFyYWN0",
            "ZXJUeXBlX0xpRnVNZW5nTWlhbhAREhoKFkNoYXJhY3RlclR5cGVfRnVFck1v",
            "U2kQEhIZChVDaGFyYWN0ZXJUeXBlX1hpYW9CYWkQExIaChZDaGFyYWN0ZXJU",
            "eXBlX1hpYW9NYUdlEBQSHgoaQ2hhcmFjdGVyVHlwZV9aaGlZZVNoYVNob3UQ",
            "FRIYChRDaGFyYWN0ZXJUeXBlX0xhb0d1aRAWEhcKE0NoYXJhY3RlclR5cGVf",
            "UWlCYWkQFxIaChZDaGFyYWN0ZXJUeXBlX0xhb1FpYW5nEBgSGwoXQ2hhcmFj",
            "dGVyVHlwZV9IZWlNZWlHdWkQGSqtAQoRQ2FyZF9UcmFuc21pdFR5cGUSGgoW",
            "Q2FyZF9UcmFuc21pdFR5cGVfTm9uZRAAEhsKF0NhcmRfVHJhbnNtaXRUeXBl",
            "X1poaURhEAESHAoYQ2FyZF9UcmFuc21pdFR5cGVfTWlEaWFuEAISHAoYQ2Fy",
            "ZF9UcmFuc21pdFR5cGVfV2VuQmVuEAMSIwofQ2FyZF9UcmFuc21pdFR5cGVf",
            "TWlEaWFuT3JaaGlEYRAEKogBChJDYXJkX0RpcmVjdGlvblR5cGUSGwoXQ2Fy",
            "ZF9EaXJlY3Rpb25UeXBlX05vbmUQABIbChdDYXJkX0RpcmVjdGlvblR5cGVf",
            "U2h1bhABEhkKFUNhcmRfRGlyZWN0aW9uVHlwZV9OaRACEh0KGUNhcmRfRGly",
            "ZWN0aW9uVHlwZV9DaG9vc2UQAyqPAQoOQ2FyZF9Db2xvclR5cGUSFwoTQ2Fy",
            "ZF9Db2xvclR5cGVfTm9uZRAAEhcKE0NhcmRfQ29sb3JUeXBlX0dyYXkQARIW",
            "ChJDYXJkX0NvbG9yVHlwZV9SZWQQAhIXChNDYXJkX0NvbG9yVHlwZV9CbHVl",
            "EAMSGgoWQ2FyZF9Db2xvclR5cGVfUmVkQmx1ZRAEKlkKDUNhcmRfTG9ja1R5",
            "cGUSFgoSQ2FyZF9Mb2NrVHlwZV9Ob25lEAASFgoSQ2FyZF9Mb2NrVHlwZV9M",
            "b2NrEAESGAoUQ2FyZF9Mb2NrVHlwZV9VbmxvY2sQAirsAQoWQ2FyZF9Hb25n",
            "S2FpV2VuQmVuVHlwZRIfChtDYXJkX0dvbmdLYWlXZW5CZW5UeXBlX05vbmUQ",
            "ABIiCh5DYXJkX0dvbmdLYWlXZW5CZW5UeXBlX0JsdWVTdWIQARIhCh1DYXJk",
            "X0dvbmdLYWlXZW5CZW5UeXBlX1JlZFN1YhACEiIKHkNhcmRfR29uZ0thaVdl",
            "bkJlblR5cGVfQmx1ZUFkZBADEiEKHUNhcmRfR29uZ0thaVdlbkJlblR5cGVf",
            "UmVkQWRkEAQSIwofQ2FyZF9Hb25nS2FpV2VuQmVuVHlwZV9HcmVlbkFkZBAF",
            "Kp0BChJDYXJkX01pTWlYaWFEYVR5cGUSGwoXQ2FyZF9NaU1pWGlhRGFUeXBl",
            "X05vbmUQABIiCh5DYXJkX01pTWlYaWFEYVR5cGVfR3JheVJlZEJ1bGUQARIi",
            "Ch5DYXJkX01pTWlYaWFEYVR5cGVfQmx1ZUdyYXlSZWQQAhIiCh5DYXJkX01p",
            "TWlYaWFEYVR5cGVfUmVkQmx1ZUdyYXkQAyrkAQoPQ2FyZF9TaGlUYW5UeXBl",
            "EhgKFENhcmRfU2hpVGFuVHlwZV9Ob25lEAASGwoXQ2FyZF9TaGlUYW5UeXBl",
            "X0JsdWVBZGQQARIaChZDYXJkX1NoaVRhblR5cGVfUmVkQWRkEAISHAoYQ2Fy",
            "ZF9TaGlUYW5UeXBlX0dyZWVuQWRkEAMSHwobQ2FyZF9TaGlUYW5UeXBlX0d1",
            "ZXNzSGFvUmVuEAQSHQoZQ2FyZF9TaGlUYW5UeXBlX0d1ZXNzV29EaRAFEiAK",
            "HENhcmRfU2hpVGFuVHlwZV9HdWVzc0ppYW5EaWUQBir/AwoQQ2FyZF9YaWFv",
            "R3VvVHlwZRIZChVDYXJkX1hpYW9HdW9UeXBlX05vbmUQABIiCh5DYXJkX1hp",
            "YW9HdW9UeXBlX0dvbmdLYWlXZW5CZW4QARIeChpDYXJkX1hpYW9HdW9UeXBl",
            "X01pTWlYaWFEYRACEhsKF0NhcmRfWGlhb0d1b1R5cGVfU2hpVGFuEAMSHAoY",
            "Q2FyZF9YaWFvR3VvVHlwZV9EaWFvQmFvEAQSGwoXQ2FyZF9YaWFvR3VvVHlw",
            "ZV9KaWVIdW8QBRIbChdDYXJkX1hpYW9HdW9UeXBlX0xpSmlhbhAGEhkKFUNh",
            "cmRfWGlhb0d1b1R5cGVfUG9ZaRAHEiEKHUNhcmRfWGlhb0d1b1R5cGVfRGlh",
            "b0h1TGlTaGFuEAgSHQoZQ2FyZF9YaWFvR3VvVHlwZV9aZW5nWXVhbhAJEhwK",
            "GENhcmRfWGlhb0d1b1R5cGVfU2hhb0h1aRAKEhwKGENhcmRfWGlhb0d1b1R5",
            "cGVfU3VvRGluZxALEiIKHkNhcmRfWGlhb0d1b1R5cGVfV2VpWGlhblFpbkJh",
            "bxAMEhoKFkNhcmRfWGlhb0d1b1R5cGVfU2hpUG8QDRIcChhDYXJkX1hpYW9H",
            "dW9UeXBlX1podWFuWWkQDhIgChxDYXJkX1hpYW9HdW9UeXBlX0ppTWlXZW5K",
            "aWFuEA9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LoginServer.Game.IdentityType), typeof(global::LoginServer.Game.CharacterType), typeof(global::LoginServer.Game.Card_TransmitType), typeof(global::LoginServer.Game.Card_DirectionType), typeof(global::LoginServer.Game.Card_ColorType), typeof(global::LoginServer.Game.Card_LockType), typeof(global::LoginServer.Game.Card_GongKaiWenBenType), typeof(global::LoginServer.Game.Card_MiMiXiaDaType), typeof(global::LoginServer.Game.Card_ShiTanType), typeof(global::LoginServer.Game.Card_XiaoGuoType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.CardType), global::LoginServer.Game.CardType.Parser, new[]{ "CardName", "Transmit", "Direction", "Color", "Lock", "Xiaoguo", "Gongkaiwenben", "Mimixiada", "Shitan" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.GameStart_C2S), global::LoginServer.Game.GameStart_C2S.Parser, new[]{ "RoomNub" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.GameStart_S2C), global::LoginServer.Game.GameStart_S2C.Parser, new[]{ "Code", "Msg" }, null, new[]{ typeof(global::LoginServer.Game.GameStart_S2C.Types.Ret_Code) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.Identity_S2C), global::LoginServer.Game.Identity_S2C.Parser, new[]{ "Identity" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.CharacterChoose_C2S), global::LoginServer.Game.CharacterChoose_C2S.Parser, new[]{ "UserName", "Character" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.CharacterChooseList_S2C), global::LoginServer.Game.CharacterChooseList_S2C.Parser, new[]{ "Characters" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.GameComplete_S2C), global::LoginServer.Game.GameComplete_S2C.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoginServer.Game.DealCards_S2C), global::LoginServer.Game.DealCards_S2C.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum IdentityType {
    [pbr::OriginalName("IdentityType_None")] None = 0,
    [pbr::OriginalName("IdentityType_TeGong")] TeGong = 1,
    [pbr::OriginalName("IdentityType_JunQing")] JunQing = 2,
    [pbr::OriginalName("IdentityType_QianFu")] QianFu = 3,
  }

  public enum CharacterType {
    [pbr::OriginalName("CharacterType_None")] None = 0,
    [pbr::OriginalName("CharacterType_LaoJin")] LaoJin = 1,
    [pbr::OriginalName("CharacterType_DaMeiNv")] DaMeiNv = 2,
    [pbr::OriginalName("CharacterType_EMeiFeng")] EmeiFeng = 3,
    [pbr::OriginalName("CharacterType_BeiLeiMao")] BeiLeiMao = 4,
    [pbr::OriginalName("CharacterType_DaoFeng")] DaoFeng = 5,
    [pbr::OriginalName("CharacterType_DaiLi")] DaiLi = 6,
    [pbr::OriginalName("CharacterType_HuangQue")] HuangQue = 7,
    [pbr::OriginalName("CharacterType_ShanLin")] ShanLin = 8,
    [pbr::OriginalName("CharacterType_FuShe")] FuShe = 9,
    [pbr::OriginalName("CharacterType_YiDianYuan")] YiDianYuan = 10,
    [pbr::OriginalName("CharacterType_LiuJie")] LiuJie = 11,
    [pbr::OriginalName("CharacterType_FuPing")] FuPing = 12,
    [pbr::OriginalName("CharacterType_QingBaoChuZhang")] QingBaoChuZhang = 13,
    [pbr::OriginalName("CharacterType_ZhiMinXiangShui")] ZhiMinXiangShui = 14,
    [pbr::OriginalName("CharacterType_GuaiDaoJiuJiu")] GuaiDaoJiuJiu = 15,
    [pbr::OriginalName("CharacterType_GangTieTeGong")] GangTieTeGong = 16,
    [pbr::OriginalName("CharacterType_LiFuMengMian")] LiFuMengMian = 17,
    [pbr::OriginalName("CharacterType_FuErMoSi")] FuErMoSi = 18,
    [pbr::OriginalName("CharacterType_XiaoBai")] XiaoBai = 19,
    [pbr::OriginalName("CharacterType_XiaoMaGe")] XiaoMaGe = 20,
    [pbr::OriginalName("CharacterType_ZhiYeShaShou")] ZhiYeShaShou = 21,
    [pbr::OriginalName("CharacterType_LaoGui")] LaoGui = 22,
    [pbr::OriginalName("CharacterType_QiBai")] QiBai = 23,
    [pbr::OriginalName("CharacterType_LaoQiang")] LaoQiang = 24,
    [pbr::OriginalName("CharacterType_HeiMeiGui")] HeiMeiGui = 25,
  }

  public enum Card_TransmitType {
    [pbr::OriginalName("Card_TransmitType_None")] None = 0,
    [pbr::OriginalName("Card_TransmitType_ZhiDa")] ZhiDa = 1,
    [pbr::OriginalName("Card_TransmitType_MiDian")] MiDian = 2,
    [pbr::OriginalName("Card_TransmitType_WenBen")] WenBen = 3,
    [pbr::OriginalName("Card_TransmitType_MiDianOrZhiDa")] MiDianOrZhiDa = 4,
  }

  public enum Card_DirectionType {
    [pbr::OriginalName("Card_DirectionType_None")] None = 0,
    [pbr::OriginalName("Card_DirectionType_Shun")] Shun = 1,
    [pbr::OriginalName("Card_DirectionType_Ni")] Ni = 2,
    [pbr::OriginalName("Card_DirectionType_Choose")] Choose = 3,
  }

  public enum Card_ColorType {
    [pbr::OriginalName("Card_ColorType_None")] None = 0,
    [pbr::OriginalName("Card_ColorType_Gray")] Gray = 1,
    [pbr::OriginalName("Card_ColorType_Red")] Red = 2,
    [pbr::OriginalName("Card_ColorType_Blue")] Blue = 3,
    [pbr::OriginalName("Card_ColorType_RedBlue")] RedBlue = 4,
  }

  public enum Card_LockType {
    [pbr::OriginalName("Card_LockType_None")] None = 0,
    [pbr::OriginalName("Card_LockType_Lock")] Lock = 1,
    [pbr::OriginalName("Card_LockType_Unlock")] Unlock = 2,
  }

  public enum Card_GongKaiWenBenType {
    [pbr::OriginalName("Card_GongKaiWenBenType_None")] None = 0,
    [pbr::OriginalName("Card_GongKaiWenBenType_BlueSub")] BlueSub = 1,
    [pbr::OriginalName("Card_GongKaiWenBenType_RedSub")] RedSub = 2,
    [pbr::OriginalName("Card_GongKaiWenBenType_BlueAdd")] BlueAdd = 3,
    [pbr::OriginalName("Card_GongKaiWenBenType_RedAdd")] RedAdd = 4,
    [pbr::OriginalName("Card_GongKaiWenBenType_GreenAdd")] GreenAdd = 5,
  }

  public enum Card_MiMiXiaDaType {
    [pbr::OriginalName("Card_MiMiXiaDaType_None")] None = 0,
    [pbr::OriginalName("Card_MiMiXiaDaType_GrayRedBule")] GrayRedBule = 1,
    [pbr::OriginalName("Card_MiMiXiaDaType_BlueGrayRed")] BlueGrayRed = 2,
    [pbr::OriginalName("Card_MiMiXiaDaType_RedBlueGray")] RedBlueGray = 3,
  }

  public enum Card_ShiTanType {
    [pbr::OriginalName("Card_ShiTanType_None")] None = 0,
    [pbr::OriginalName("Card_ShiTanType_BlueAdd")] BlueAdd = 1,
    [pbr::OriginalName("Card_ShiTanType_RedAdd")] RedAdd = 2,
    [pbr::OriginalName("Card_ShiTanType_GreenAdd")] GreenAdd = 3,
    [pbr::OriginalName("Card_ShiTanType_GuessHaoRen")] GuessHaoRen = 4,
    [pbr::OriginalName("Card_ShiTanType_GuessWoDi")] GuessWoDi = 5,
    [pbr::OriginalName("Card_ShiTanType_GuessJianDie")] GuessJianDie = 6,
  }

  public enum Card_XiaoGuoType {
    [pbr::OriginalName("Card_XiaoGuoType_None")] None = 0,
    [pbr::OriginalName("Card_XiaoGuoType_GongKaiWenBen")] GongKaiWenBen = 1,
    [pbr::OriginalName("Card_XiaoGuoType_MiMiXiaDa")] MiMiXiaDa = 2,
    [pbr::OriginalName("Card_XiaoGuoType_ShiTan")] ShiTan = 3,
    [pbr::OriginalName("Card_XiaoGuoType_DiaoBao")] DiaoBao = 4,
    [pbr::OriginalName("Card_XiaoGuoType_JieHuo")] JieHuo = 5,
    [pbr::OriginalName("Card_XiaoGuoType_LiJian")] LiJian = 6,
    [pbr::OriginalName("Card_XiaoGuoType_PoYi")] PoYi = 7,
    [pbr::OriginalName("Card_XiaoGuoType_DiaoHuLiShan")] DiaoHuLiShan = 8,
    [pbr::OriginalName("Card_XiaoGuoType_ZengYuan")] ZengYuan = 9,
    [pbr::OriginalName("Card_XiaoGuoType_ShaoHui")] ShaoHui = 10,
    [pbr::OriginalName("Card_XiaoGuoType_SuoDing")] SuoDing = 11,
    [pbr::OriginalName("Card_XiaoGuoType_WeiXianQinBao")] WeiXianQinBao = 12,
    [pbr::OriginalName("Card_XiaoGuoType_ShiPo")] ShiPo = 13,
    [pbr::OriginalName("Card_XiaoGuoType_ZhuanYi")] ZhuanYi = 14,
    [pbr::OriginalName("Card_XiaoGuoType_JiMiWenJian")] JiMiWenJian = 15,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CardType : pb::IMessage<CardType>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CardType> _parser = new pb::MessageParser<CardType>(() => new CardType());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CardType> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardType() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardType(CardType other) : this() {
      cardName_ = other.cardName_;
      transmit_ = other.transmit_;
      direction_ = other.direction_;
      color_ = other.color_;
      lock_ = other.lock_;
      xiaoguo_ = other.xiaoguo_;
      gongkaiwenben_ = other.gongkaiwenben_;
      mimixiada_ = other.mimixiada_;
      shitan_ = other.shitan_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardType Clone() {
      return new CardType(this);
    }

    /// <summary>Field number for the "cardName" field.</summary>
    public const int CardNameFieldNumber = 1;
    private string cardName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CardName {
      get { return cardName_; }
      set {
        cardName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transmit" field.</summary>
    public const int TransmitFieldNumber = 2;
    private global::LoginServer.Game.Card_TransmitType transmit_ = global::LoginServer.Game.Card_TransmitType.None;
    /// <summary>
    ///传递方式
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_TransmitType Transmit {
      get { return transmit_; }
      set {
        transmit_ = value;
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 3;
    private global::LoginServer.Game.Card_DirectionType direction_ = global::LoginServer.Game.Card_DirectionType.None;
    /// <summary>
    ///传递方向
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_DirectionType Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 4;
    private global::LoginServer.Game.Card_ColorType color_ = global::LoginServer.Game.Card_ColorType.None;
    /// <summary>
    ///阵营
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_ColorType Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "lock" field.</summary>
    public const int LockFieldNumber = 5;
    private global::LoginServer.Game.Card_LockType lock_ = global::LoginServer.Game.Card_LockType.None;
    /// <summary>
    ///是否可毁坏
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_LockType Lock {
      get { return lock_; }
      set {
        lock_ = value;
      }
    }

    /// <summary>Field number for the "xiaoguo" field.</summary>
    public const int XiaoguoFieldNumber = 6;
    private global::LoginServer.Game.Card_XiaoGuoType xiaoguo_ = global::LoginServer.Game.Card_XiaoGuoType.None;
    /// <summary>
    ///效果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_XiaoGuoType Xiaoguo {
      get { return xiaoguo_; }
      set {
        xiaoguo_ = value;
      }
    }

    /// <summary>Field number for the "gongkaiwenben" field.</summary>
    public const int GongkaiwenbenFieldNumber = 7;
    private global::LoginServer.Game.Card_GongKaiWenBenType gongkaiwenben_ = global::LoginServer.Game.Card_GongKaiWenBenType.None;
    /// <summary>
    ///公开文本特殊类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_GongKaiWenBenType Gongkaiwenben {
      get { return gongkaiwenben_; }
      set {
        gongkaiwenben_ = value;
      }
    }

    /// <summary>Field number for the "mimixiada" field.</summary>
    public const int MimixiadaFieldNumber = 8;
    private global::LoginServer.Game.Card_MiMiXiaDaType mimixiada_ = global::LoginServer.Game.Card_MiMiXiaDaType.None;
    /// <summary>
    ///秘密下达特殊类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_MiMiXiaDaType Mimixiada {
      get { return mimixiada_; }
      set {
        mimixiada_ = value;
      }
    }

    /// <summary>Field number for the "shitan" field.</summary>
    public const int ShitanFieldNumber = 9;
    private global::LoginServer.Game.Card_ShiTanType shitan_ = global::LoginServer.Game.Card_ShiTanType.None;
    /// <summary>
    ///试探特殊类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.Card_ShiTanType Shitan {
      get { return shitan_; }
      set {
        shitan_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CardType);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CardType other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CardName != other.CardName) return false;
      if (Transmit != other.Transmit) return false;
      if (Direction != other.Direction) return false;
      if (Color != other.Color) return false;
      if (Lock != other.Lock) return false;
      if (Xiaoguo != other.Xiaoguo) return false;
      if (Gongkaiwenben != other.Gongkaiwenben) return false;
      if (Mimixiada != other.Mimixiada) return false;
      if (Shitan != other.Shitan) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CardName.Length != 0) hash ^= CardName.GetHashCode();
      if (Transmit != global::LoginServer.Game.Card_TransmitType.None) hash ^= Transmit.GetHashCode();
      if (Direction != global::LoginServer.Game.Card_DirectionType.None) hash ^= Direction.GetHashCode();
      if (Color != global::LoginServer.Game.Card_ColorType.None) hash ^= Color.GetHashCode();
      if (Lock != global::LoginServer.Game.Card_LockType.None) hash ^= Lock.GetHashCode();
      if (Xiaoguo != global::LoginServer.Game.Card_XiaoGuoType.None) hash ^= Xiaoguo.GetHashCode();
      if (Gongkaiwenben != global::LoginServer.Game.Card_GongKaiWenBenType.None) hash ^= Gongkaiwenben.GetHashCode();
      if (Mimixiada != global::LoginServer.Game.Card_MiMiXiaDaType.None) hash ^= Mimixiada.GetHashCode();
      if (Shitan != global::LoginServer.Game.Card_ShiTanType.None) hash ^= Shitan.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CardName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CardName);
      }
      if (Transmit != global::LoginServer.Game.Card_TransmitType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Transmit);
      }
      if (Direction != global::LoginServer.Game.Card_DirectionType.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Direction);
      }
      if (Color != global::LoginServer.Game.Card_ColorType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Color);
      }
      if (Lock != global::LoginServer.Game.Card_LockType.None) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Lock);
      }
      if (Xiaoguo != global::LoginServer.Game.Card_XiaoGuoType.None) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Xiaoguo);
      }
      if (Gongkaiwenben != global::LoginServer.Game.Card_GongKaiWenBenType.None) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Gongkaiwenben);
      }
      if (Mimixiada != global::LoginServer.Game.Card_MiMiXiaDaType.None) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Mimixiada);
      }
      if (Shitan != global::LoginServer.Game.Card_ShiTanType.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) Shitan);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CardName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CardName);
      }
      if (Transmit != global::LoginServer.Game.Card_TransmitType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Transmit);
      }
      if (Direction != global::LoginServer.Game.Card_DirectionType.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Direction);
      }
      if (Color != global::LoginServer.Game.Card_ColorType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Color);
      }
      if (Lock != global::LoginServer.Game.Card_LockType.None) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Lock);
      }
      if (Xiaoguo != global::LoginServer.Game.Card_XiaoGuoType.None) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Xiaoguo);
      }
      if (Gongkaiwenben != global::LoginServer.Game.Card_GongKaiWenBenType.None) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Gongkaiwenben);
      }
      if (Mimixiada != global::LoginServer.Game.Card_MiMiXiaDaType.None) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Mimixiada);
      }
      if (Shitan != global::LoginServer.Game.Card_ShiTanType.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) Shitan);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CardName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CardName);
      }
      if (Transmit != global::LoginServer.Game.Card_TransmitType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Transmit);
      }
      if (Direction != global::LoginServer.Game.Card_DirectionType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Direction);
      }
      if (Color != global::LoginServer.Game.Card_ColorType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Color);
      }
      if (Lock != global::LoginServer.Game.Card_LockType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Lock);
      }
      if (Xiaoguo != global::LoginServer.Game.Card_XiaoGuoType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Xiaoguo);
      }
      if (Gongkaiwenben != global::LoginServer.Game.Card_GongKaiWenBenType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gongkaiwenben);
      }
      if (Mimixiada != global::LoginServer.Game.Card_MiMiXiaDaType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Mimixiada);
      }
      if (Shitan != global::LoginServer.Game.Card_ShiTanType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Shitan);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CardType other) {
      if (other == null) {
        return;
      }
      if (other.CardName.Length != 0) {
        CardName = other.CardName;
      }
      if (other.Transmit != global::LoginServer.Game.Card_TransmitType.None) {
        Transmit = other.Transmit;
      }
      if (other.Direction != global::LoginServer.Game.Card_DirectionType.None) {
        Direction = other.Direction;
      }
      if (other.Color != global::LoginServer.Game.Card_ColorType.None) {
        Color = other.Color;
      }
      if (other.Lock != global::LoginServer.Game.Card_LockType.None) {
        Lock = other.Lock;
      }
      if (other.Xiaoguo != global::LoginServer.Game.Card_XiaoGuoType.None) {
        Xiaoguo = other.Xiaoguo;
      }
      if (other.Gongkaiwenben != global::LoginServer.Game.Card_GongKaiWenBenType.None) {
        Gongkaiwenben = other.Gongkaiwenben;
      }
      if (other.Mimixiada != global::LoginServer.Game.Card_MiMiXiaDaType.None) {
        Mimixiada = other.Mimixiada;
      }
      if (other.Shitan != global::LoginServer.Game.Card_ShiTanType.None) {
        Shitan = other.Shitan;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CardName = input.ReadString();
            break;
          }
          case 16: {
            Transmit = (global::LoginServer.Game.Card_TransmitType) input.ReadEnum();
            break;
          }
          case 24: {
            Direction = (global::LoginServer.Game.Card_DirectionType) input.ReadEnum();
            break;
          }
          case 32: {
            Color = (global::LoginServer.Game.Card_ColorType) input.ReadEnum();
            break;
          }
          case 40: {
            Lock = (global::LoginServer.Game.Card_LockType) input.ReadEnum();
            break;
          }
          case 48: {
            Xiaoguo = (global::LoginServer.Game.Card_XiaoGuoType) input.ReadEnum();
            break;
          }
          case 56: {
            Gongkaiwenben = (global::LoginServer.Game.Card_GongKaiWenBenType) input.ReadEnum();
            break;
          }
          case 64: {
            Mimixiada = (global::LoginServer.Game.Card_MiMiXiaDaType) input.ReadEnum();
            break;
          }
          case 72: {
            Shitan = (global::LoginServer.Game.Card_ShiTanType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CardName = input.ReadString();
            break;
          }
          case 16: {
            Transmit = (global::LoginServer.Game.Card_TransmitType) input.ReadEnum();
            break;
          }
          case 24: {
            Direction = (global::LoginServer.Game.Card_DirectionType) input.ReadEnum();
            break;
          }
          case 32: {
            Color = (global::LoginServer.Game.Card_ColorType) input.ReadEnum();
            break;
          }
          case 40: {
            Lock = (global::LoginServer.Game.Card_LockType) input.ReadEnum();
            break;
          }
          case 48: {
            Xiaoguo = (global::LoginServer.Game.Card_XiaoGuoType) input.ReadEnum();
            break;
          }
          case 56: {
            Gongkaiwenben = (global::LoginServer.Game.Card_GongKaiWenBenType) input.ReadEnum();
            break;
          }
          case 64: {
            Mimixiada = (global::LoginServer.Game.Card_MiMiXiaDaType) input.ReadEnum();
            break;
          }
          case 72: {
            Shitan = (global::LoginServer.Game.Card_ShiTanType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///0x0200
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameStart_C2S : pb::IMessage<GameStart_C2S>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameStart_C2S> _parser = new pb::MessageParser<GameStart_C2S>(() => new GameStart_C2S());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameStart_C2S> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameStart_C2S() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameStart_C2S(GameStart_C2S other) : this() {
      roomNub_ = other.roomNub_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameStart_C2S Clone() {
      return new GameStart_C2S(this);
    }

    /// <summary>Field number for the "roomNub" field.</summary>
    public const int RoomNubFieldNumber = 1;
    private int roomNub_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomNub {
      get { return roomNub_; }
      set {
        roomNub_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameStart_C2S);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameStart_C2S other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomNub != other.RoomNub) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomNub != 0) hash ^= RoomNub.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomNub != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomNub);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomNub != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RoomNub);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomNub != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomNub);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameStart_C2S other) {
      if (other == null) {
        return;
      }
      if (other.RoomNub != 0) {
        RoomNub = other.RoomNub;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomNub = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomNub = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///0x0200
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameStart_S2C : pb::IMessage<GameStart_S2C>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameStart_S2C> _parser = new pb::MessageParser<GameStart_S2C>(() => new GameStart_S2C());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameStart_S2C> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameStart_S2C() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameStart_S2C(GameStart_S2C other) : this() {
      code_ = other.code_;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameStart_S2C Clone() {
      return new GameStart_S2C(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::LoginServer.Game.GameStart_S2C.Types.Ret_Code code_ = global::LoginServer.Game.GameStart_S2C.Types.Ret_Code.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.GameStart_S2C.Types.Ret_Code Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameStart_S2C);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameStart_S2C other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::LoginServer.Game.GameStart_S2C.Types.Ret_Code.Success) hash ^= Code.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != global::LoginServer.Game.GameStart_S2C.Types.Ret_Code.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != global::LoginServer.Game.GameStart_S2C.Types.Ret_Code.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::LoginServer.Game.GameStart_S2C.Types.Ret_Code.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameStart_S2C other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::LoginServer.Game.GameStart_S2C.Types.Ret_Code.Success) {
        Code = other.Code;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::LoginServer.Game.GameStart_S2C.Types.Ret_Code) input.ReadEnum();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = (global::LoginServer.Game.GameStart_S2C.Types.Ret_Code) input.ReadEnum();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GameStart_S2C message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Ret_Code {
        [pbr::OriginalName("Success")] Success = 0,
        [pbr::OriginalName("Failed")] Failed = 1,
      }

    }
    #endregion

  }

  /// <summary>
  ///0x0201
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Identity_S2C : pb::IMessage<Identity_S2C>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Identity_S2C> _parser = new pb::MessageParser<Identity_S2C>(() => new Identity_S2C());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Identity_S2C> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Identity_S2C() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Identity_S2C(Identity_S2C other) : this() {
      identity_ = other.identity_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Identity_S2C Clone() {
      return new Identity_S2C(this);
    }

    /// <summary>Field number for the "identity" field.</summary>
    public const int IdentityFieldNumber = 1;
    private global::LoginServer.Game.IdentityType identity_ = global::LoginServer.Game.IdentityType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.IdentityType Identity {
      get { return identity_; }
      set {
        identity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Identity_S2C);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Identity_S2C other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Identity != other.Identity) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Identity != global::LoginServer.Game.IdentityType.None) hash ^= Identity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Identity != global::LoginServer.Game.IdentityType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Identity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Identity != global::LoginServer.Game.IdentityType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Identity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Identity != global::LoginServer.Game.IdentityType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Identity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Identity_S2C other) {
      if (other == null) {
        return;
      }
      if (other.Identity != global::LoginServer.Game.IdentityType.None) {
        Identity = other.Identity;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Identity = (global::LoginServer.Game.IdentityType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Identity = (global::LoginServer.Game.IdentityType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///0x0202
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CharacterChoose_C2S : pb::IMessage<CharacterChoose_C2S>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CharacterChoose_C2S> _parser = new pb::MessageParser<CharacterChoose_C2S>(() => new CharacterChoose_C2S());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CharacterChoose_C2S> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterChoose_C2S() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterChoose_C2S(CharacterChoose_C2S other) : this() {
      userName_ = other.userName_;
      character_ = other.character_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterChoose_C2S Clone() {
      return new CharacterChoose_C2S(this);
    }

    /// <summary>Field number for the "userName" field.</summary>
    public const int UserNameFieldNumber = 1;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "character" field.</summary>
    public const int CharacterFieldNumber = 2;
    private global::LoginServer.Game.CharacterType character_ = global::LoginServer.Game.CharacterType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoginServer.Game.CharacterType Character {
      get { return character_; }
      set {
        character_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CharacterChoose_C2S);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CharacterChoose_C2S other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserName != other.UserName) return false;
      if (Character != other.Character) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (Character != global::LoginServer.Game.CharacterType.None) hash ^= Character.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (Character != global::LoginServer.Game.CharacterType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Character);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (Character != global::LoginServer.Game.CharacterType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Character);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (Character != global::LoginServer.Game.CharacterType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Character);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CharacterChoose_C2S other) {
      if (other == null) {
        return;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.Character != global::LoginServer.Game.CharacterType.None) {
        Character = other.Character;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 16: {
            Character = (global::LoginServer.Game.CharacterType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 16: {
            Character = (global::LoginServer.Game.CharacterType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///0x0203
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CharacterChooseList_S2C : pb::IMessage<CharacterChooseList_S2C>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CharacterChooseList_S2C> _parser = new pb::MessageParser<CharacterChooseList_S2C>(() => new CharacterChooseList_S2C());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CharacterChooseList_S2C> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterChooseList_S2C() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterChooseList_S2C(CharacterChooseList_S2C other) : this() {
      characters_ = other.characters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterChooseList_S2C Clone() {
      return new CharacterChooseList_S2C(this);
    }

    /// <summary>Field number for the "characters" field.</summary>
    public const int CharactersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::LoginServer.Game.CharacterType> _repeated_characters_codec
        = pb::FieldCodec.ForEnum(10, x => (int) x, x => (global::LoginServer.Game.CharacterType) x);
    private readonly pbc::RepeatedField<global::LoginServer.Game.CharacterType> characters_ = new pbc::RepeatedField<global::LoginServer.Game.CharacterType>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::LoginServer.Game.CharacterType> Characters {
      get { return characters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CharacterChooseList_S2C);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CharacterChooseList_S2C other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!characters_.Equals(other.characters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= characters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      characters_.WriteTo(output, _repeated_characters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      characters_.WriteTo(ref output, _repeated_characters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += characters_.CalculateSize(_repeated_characters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CharacterChooseList_S2C other) {
      if (other == null) {
        return;
      }
      characters_.Add(other.characters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            characters_.AddEntriesFrom(input, _repeated_characters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            characters_.AddEntriesFrom(ref input, _repeated_characters_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///0x0204
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameComplete_S2C : pb::IMessage<GameComplete_S2C>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameComplete_S2C> _parser = new pb::MessageParser<GameComplete_S2C>(() => new GameComplete_S2C());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameComplete_S2C> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameComplete_S2C() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameComplete_S2C(GameComplete_S2C other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameComplete_S2C Clone() {
      return new GameComplete_S2C(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameComplete_S2C);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameComplete_S2C other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameComplete_S2C other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  ///0x0205
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DealCards_S2C : pb::IMessage<DealCards_S2C>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DealCards_S2C> _parser = new pb::MessageParser<DealCards_S2C>(() => new DealCards_S2C());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DealCards_S2C> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoginServer.Game.LoginServerGameReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DealCards_S2C() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DealCards_S2C(DealCards_S2C other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DealCards_S2C Clone() {
      return new DealCards_S2C(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DealCards_S2C);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DealCards_S2C other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DealCards_S2C other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
